//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int DoctorId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> MedicalCenterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual MedicalCenter MedicalCenter { get; set; }
        public IEnumerable<SelectListItem> MedicalCentersList { get; set; }
    }
}
